version: "3.7"

services:
  frontend:
    container_name: "frontend"
    build: "./frontend"
    volumes:
      - ./frontend:/var/app/frontend
      - /var/app/frontend/node_modules
    tty: true
    ports:
      - 3001:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
